<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8EjX0nh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8EjX0nh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8EjX0nh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8EjX0nh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8EjX0nh\App_KernelDevDebugContainer([
    'container.build_hash' => '8EjX0nh',
    'container.build_id' => '2bb0fffc',
    'container.build_time' => 1604572881,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8EjX0nh');
